export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GEOCODING_FETCHING = 'GEOCODING_FETCHING'
export const GEOCODING_FETCHING_SUCCESS = 'GEOCODING_FETCHING_SUCCESS'
export const GEOCODING_FETCHING_FAIL = 'GEOCODING_FETCHING_FAIL'