export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESSS = 'REGISTER_SUCCESSS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GEOCODING_FETCHING = 'GEOCODING_FETCHING'
export const GEOCODING_FETCHING_SUCCESS = 'GEOCODING_FETCHING_SUCCESS'
export const GEOCODING_FETCHING_FAIL = 'GEOCODING_FETCHING_FAIL'

export const ITER_FETCHING = 'ITER_FETCHING'
export const ITER_FETCHING_SUCCESS = 'ITER_FETCHING_SUCCESS'
export const ITER_FETCHING_FAIL = 'ITER_FETCHING_FAIL'